package cmd

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// configFileName is the name of the config file `quasar init` scaffolds.
const configFileName = ".quasar.yaml"

// initCmd scaffolds a .quasar.yaml in the working directory with sensible
// auto-detected defaults.
var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Scaffold a .quasar.yaml in the current directory",
	Long: "Create a .quasar.yaml in the working directory, auto-detecting the " +
		"project language for [verify] and the GitHub origin remote for " +
		"[integrations.github]. Refuses to overwrite an existing file unless " +
		"--force is given.",
	RunE:          runInit,
	SilenceUsage:  true,
	SilenceErrors: true,
}

func init() {
	initCmd.Flags().Bool("force", false, "Overwrite an existing .quasar.yaml")
	initCmd.Flags().Bool("yes", false, "Skip the overwrite confirmation prompt (requires --force)")
	rootCmd.AddCommand(initCmd)
}

// runInit is the cobra adapter for `quasar init`. It resolves the working
// directory and flags, then delegates to runInitWith with production I/O.
func runInit(cmd *cobra.Command, _ []string) error {
	wd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("resolve working directory: %w", err)
	}
	force, _ := cmd.Flags().GetBool("force")
	yes, _ := cmd.Flags().GetBool("yes")

	return runInitWith(wd, force, yes, cmd.InOrStdin(), cmd.ErrOrStderr())
}

// runInitWith is the dependency-injected core of init. dir is the directory the
// config is written to; in/out are the confirmation prompt's I/O streams so
// tests can drive the --force overwrite path without a real TTY.
func runInitWith(dir string, force, yes bool, in io.Reader, out io.Writer) error {
	path := filepath.Join(dir, configFileName)

	if _, err := os.Stat(path); err == nil {
		if !force {
			return fmt.Errorf("%s already exists; pass --force to overwrite", configFileName)
		}
		if !yes && !confirmOverwrite(in, out) {
			fmt.Fprintln(out, "aborted; existing file left unchanged")
			return nil
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", path, err)
	}

	verify := detectVerifyCommands(dir)
	repo, hasRepo := detectGitHubRepo(dir)
	content := renderConfigTemplate(verify, repo, hasRepo)

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", configFileName, err)
	}

	fmt.Fprintf(out, "created %s\n", path)
	reportDetections(out, verify, repo, hasRepo)
	fmt.Fprintf(out, "edit %s to fill in integrations and pre-commit hooks, then run `quasar doctor`\n", configFileName)
	return nil
}

// confirmOverwrite prompts on out and reads a yes/no answer from in. Any answer
// other than "y"/"yes" (case-insensitive) is treated as a decline.
func confirmOverwrite(in io.Reader, out io.Writer) bool {
	fmt.Fprintf(out, "%s already exists. Overwrite? [y/N]: ", configFileName)
	scanner := bufio.NewScanner(in)
	if !scanner.Scan() {
		return false
	}
	answer := strings.ToLower(strings.TrimSpace(scanner.Text()))
	return answer == "y" || answer == "yes"
}

// reportDetections prints a short summary of what init auto-detected so the user
// knows which sections were pre-populated versus left as placeholders.
func reportDetections(out io.Writer, v verifyCommands, repo string, hasRepo bool) {
	if v.Lang != "" {
		fmt.Fprintf(out, "  detected language: %s ([verify] populated)\n", v.Lang)
	} else {
		fmt.Fprintln(out, "  language: not detected ([verify] left commented out)")
	}
	if hasRepo {
		fmt.Fprintf(out, "  detected GitHub repo: %s ([integrations.github].repo populated)\n", repo)
	} else {
		fmt.Fprintln(out, "  GitHub remote: not detected ([integrations.github] left commented out)")
	}
}

// renderConfigTemplate builds the .quasar.yaml body. Detected sections are
// written live; undetected ones are emitted as commented placeholders so the
// file always documents every section. Secrets are never written: the
// integration block references token_env / token_file only.
func renderConfigTemplate(v verifyCommands, repo string, hasRepo bool) string {
	var b strings.Builder

	b.WriteString("# Quasar configuration — generated by `quasar init`.\n")
	b.WriteString("# Edit the placeholders below, then run `quasar doctor` to validate.\n\n")

	b.WriteString("# Path to the claude CLI binary.\n")
	b.WriteString("claude_path: claude\n\n")

	b.WriteString("# Safety limits for the coder-reviewer loop.\n")
	b.WriteString("max_review_cycles: 3\n")
	b.WriteString("max_budget_usd: 5.0\n\n")

	b.WriteString("# Claude model (empty = CLI default).\n")
	b.WriteString("model: \"\"\n\n")

	writeVerifySection(&b, v)
	writeIntegrationsSection(&b, repo, hasRepo)
	writeForgeSection(&b)
	writePreCommitSection(&b)

	return b.String()
}

// writeVerifySection emits [verify]. Detected commands are written live; when no
// language was detected the whole block is commented out with an example.
func writeVerifySection(b *strings.Builder, v verifyCommands) {
	b.WriteString("# Verification gates (reserved; enforced in a later release).\n")
	if v.Lang == "" {
		b.WriteString("# Detected no known project markers; uncomment and fill in:\n")
		b.WriteString("# verify:\n")
		b.WriteString("#   test: \"go test ./...\"\n")
		b.WriteString("#   lint: \"go vet ./...\"\n")
		b.WriteString("#   build: \"go build ./...\"\n\n")
		return
	}
	fmt.Fprintf(b, "# Detected %s.\n", v.Lang)
	b.WriteString("verify:\n")
	fmt.Fprintf(b, "  test: %q\n", v.Test)
	fmt.Fprintf(b, "  lint: %q\n", v.Lint)
	fmt.Fprintf(b, "  build: %q\n\n", v.Build)
}

// writeIntegrationsSection emits [integrations.github]. The repo is written live
// when detected; the credential reference is always a placeholder pointing at an
// env var — a token value is never written to the file.
func writeIntegrationsSection(b *strings.Builder, repo string, hasRepo bool) {
	b.WriteString("# External ticket sources. Tokens are NEVER stored here: set\n")
	b.WriteString("# token_env (an env var name) or token_file (a Docker secret path).\n")
	if !hasRepo {
		b.WriteString("# No github.com origin detected; uncomment and set repo:\n")
		b.WriteString("# integrations:\n")
		b.WriteString("#   github:\n")
		b.WriteString("#     repo: \"owner/repo\"\n")
		b.WriteString("#     token_env: \"GITHUB_TOKEN\"\n")
		b.WriteString("#     # token_file: \"/run/secrets/github_token\"\n\n")
		return
	}
	b.WriteString("integrations:\n")
	b.WriteString("  github:\n")
	fmt.Fprintf(b, "    repo: %q\n", repo)
	b.WriteString("    token_env: \"GITHUB_TOKEN\"\n")
	b.WriteString("    # token_file: \"/run/secrets/github_token\"\n\n")
}

// writeForgeSection emits the reserved [forge.github] placeholder. The forge
// (PR-creation) surface is reserved; this documents the schema without enabling
// anything in the current release.
func writeForgeSection(b *strings.Builder) {
	b.WriteString("# Forge (PR creation) — reserved for a later release.\n")
	b.WriteString("# forge:\n")
	b.WriteString("#   github:\n")
	b.WriteString("#     repo: \"owner/repo\"\n")
	b.WriteString("#     token_env: \"GITHUB_TOKEN\"\n\n")
}

// writePreCommitSection emits [pre_commit] with an empty command list and a
// commented example of common formatters for the user to uncomment.
func writePreCommitSection(b *strings.Builder) {
	b.WriteString("# Commands run in the worktree before every Quasar commit.\n")
	b.WriteString("pre_commit:\n")
	b.WriteString("  commands: []\n")
	b.WriteString("  fail_on_error: true\n")
	b.WriteString("  # Uncomment the formatters relevant to your project:\n")
	b.WriteString("  # commands:\n")
	b.WriteString("  #   - \"gofmt -w .\"\n")
	b.WriteString("  #   - \"tofu fmt\"\n")
	b.WriteString("  #   - \"prettier --write .\"\n")
	b.WriteString("  #   - \"ruff format .\"\n")
	b.WriteString("  #   - \"cargo fmt\"\n")
}
